inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'test/hash/bla.rb'

Metrics/LineLength:
  Exclude:
    - test/diagram_test.rb

Naming/MethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# DISCUSS: user map instead of collect
Style/CollectionMethods:
  Enabled: false

# DISCUSS: Use raise with an explicit exception class and message, rather than just a message
Style/ImplicitRuntimeError:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

# DISCUSS: Use fail instead of raise to signal exceptions
Style/SignalException:
  Enabled: false

# DISUSS: this could be false because we have if locals blabla
Bundler/DuplicatedGem:
  Enabled: false
